version: "3.5"

services:
  balancer_1:
    build: 
      context: .
      dockerfile: ./docker/dev.Dockerfile
    container_name: balancer_1
    ports:
      - 8000:8000
    networks:
      - balancer_network
    restart: always
    env_file:
      - dev.env
    volumes:
      - ./var/log/app:/var/log/app

  balancer_2:
    build: 
      context: .
      dockerfile: ./docker/dev.Dockerfile
    container_name: balancer_2
    ports:
      - 8001:8000
    networks:
      - balancer_network
    restart: always
    env_file:
      - dev.env
    # volumes:
      # - ./var/log/app:/var/log/app

networks:
  balancer_network:
    external: true