version: "3.5"

services:
  redis:
    image: bitnami/redis:latest
    networks:
      - balancer_network
    container_name: redis
    restart: always
    env_file:
      - redis.env
    sysctls:
      net.core.somaxconn: '1011'

networks:
  balancer_network: